### ISSUE TITLE
Fails on MacOS

### ISSUE THREAD

**Issue by juris** [cornelius-keller/ansible-ovh#4]
Module fails on MacOS with the following error:

```
ImportError: No module named ovh
```

because of:

```
#!/usr/bin/python
```

And works fine if I change it to more robust:

```
#!/usr/bin/env python
```

Please update your wonderful wrapper. Thanks!

**Comment by cornelius-keller** [comment]
Hi @juris,
I changed it according to your suggestion.
Can you confirm it works on a mac now?

**Comment by juris** [comment]
Works!
Thank you.
